### ISSUE TITLE
[Enhancement] Increase the number of cells in the background of the curve creation.

### ISSUE THREAD

**Issue by OlegEnot** [NGnius/Fantastic#14]
Hi all!
In the current version, there is a grid at the place where the curve is created, but the number of cells along two axes is 8*8 pcs. Which is very non-intuitive (100/8=12.5).
It may be possible to implement 10 * 10 cells, as well as duplicate the middle axes of the legend:

100%
 |
50%
 |
0---50°C---100°C

![steamuserimages-a akamaihd01](https://github.com/NGnius/Fantastic/assets/121382147/7a5c3c65-6336-4e86-8c48-8bb7deac1a1c)

Thank you!

**Comment by NGnius** [comment]
I'm not against changing it, but I do contest the claim that it's unintuitive.

8 is 2^3, which means it's easy to find half subdivisions (50%, 25%, 12.5%). Anecdotally, I've seen that humans do well with halves -- ask someone to cut something in 2 without measuring and the pieces will be pretty even. Ask them to cut something in 4 and they may do alright. Ask them to cut something in 2 and then those halves in 2, and they'll probably do better. Cutting something into 5 will be a horrible experience. I've had similar experience with mental math.

10 sort of sucks because it's only got two factors (2 and 5) which makes it hard to read quickly. Someone who needs that sort of accuracy might be better off just editing the JSON config.

**Comment by OlegEnot** [comment]
You know, you're really right. If you think about it like that, then it is quite intuitive to operate with such shares. Thank you!
