### ISSUE TITLE
Fantastic 0.3.1 after install does not show the graph

### ISSUE THREAD

**Issue by donannis** [NGnius/Fantastic#4]
the graph that was showing up in 0.3.0 does not show up on new folder install to the plugins directory. cannot set fan curve.

**Comment by NGnius** [comment]
I'm just going to throw some standard troubleshooting question at you because I don't know what's happened. In no particular order, have you tried:

- [ ] Reinstalling, including re-downloading the latest release zip?
- [ ] Restarting your Deck?
- [ ] Uninstalling, then reinstalling Fantastic?

If none of those work, can you grab the `/tmp/fantastic.py.log` and `/tmp/fantastic.log` files from your Deck so I can get a better idea of what's going wrong.

**Comment by gipawu** [comment]
I have the same trouble.

Log files are empty (just "[INFO] Starting back-end (fantastic-rs v0.3.1)" and "INFO Fantastic main.py https://github.com/NGnius/Fantastic")

**Comment by donannis** [comment]
I just extracted the folder into the plugins directory like all the other versions. no graph. it's sitting in /plugins/Fantastic-v0.3.1/ folder.

**Comment by NGnius** [comment]
Installing from the archive containing the built version of the plugin, and not one of the source archives? Is there anything else running on your system that's using port 44444 (like an older version of Fantastic, or some other server)?
